### ISSUE TITLE
Generated JSON-files are not accepted for upload in API-Playground

### ISSUE THREAD

**Issue by RobertLang** [sphereio/sphere-product-type-json-generator#15]
I created a product type with this generator and try to upload it using API-Playgrounds endpoint ProductType/create but the file gets rejected. Pasting the files content into payload works.

![image](https://cloud.githubusercontent.com/assets/6792844/4860212/9e541c60-60f4-11e4-97cf-b6b3bc22424c.png)

**Comment by stmeissner** [comment]
just guessing in the dark: It could be caused by "wrong" double quotation marks in JSON files
‟ (U + 201F) double high-reversed-9 quotation mark 
vs.
” (U + 201D) right double quotation mark
