### ISSUE TITLE
generates invalid JSON for "Set of Reference Type" attributes

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-product-type-json-generator#19]
This tool generated invalid JSON when used for a certain type of Attribute: Set of Reference Type
the content of the 'type' column was 'set:reference:product'

the generated JSON lacks in the lines 
"isRequired": false,
"isSearchable": false
that had to be added manually to the Attribute definition.

**Comment by hajoeichler** [comment]
see https://github.com/sphereio/sphere-product-type-json-generator/commit/17ce3575b7fefe845ac24ca91625d0d669a0bbd9

**Comment by hajoeichler** [comment]
I think this is related to #15
