### ISSUE TITLE
update package on npmjs

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-product-type-json-generator#23]
The last version published on https://www.npmjs.com/package/sphere-product-type-json-generator is 9 months old. In the meanwhile the dependencies have been updated.

**Comment by emtii** [comment]
Yes, please update npm according your releases :+1:

**Comment by sebbulon** [comment]
Hi @emtii, I made a release of the latest version and published it to the NPM repository. 
cheers!

**Comment by emtii** [comment]
Thx! :+1:
