### ISSUE TITLE
add switch to cli to create just one json file instead of one file per product type

### ISSUE THREAD

**Issue by emtii** [sphereio/sphere-product-type-json-generator#26]
Headline describes, but:

As a customer I would like to cd into /sphere-product-type-json-generator/ and type ./bin/product-type-generator --help and see a new switch in this short manpage explaining how to create just one json file for all product types instead of one file per product type.

**Comment by mmoelli** [comment]
@emtii This is a bit tricky. For the API, we actually need one file per productType as the creation is a POST with JSON payload for one productType. Having several productTypes in one file would need an adjustment in the API and would be not just only a tooling issue.

**Comment by emtii** [comment]
Oh - I see - Sorry, was a bit too fast. Okay - thx - then I know how to do it :+1: 

In relation to that, just for the ppl who look for a easy solution to concatenate files, its easy, type:

> cat foo1.json foo2.json >> bar.json

Will chain foo2 directly at the end of foo1. Just didnt know myself about that, so... going to share that here. Can be closed then :)

**Comment by mmoelli** [comment]
Thanks for the feedback.
