### ISSUE TITLE
isSearchable not evaluated for set of enum and set of localized enum attributes

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-product-type-json-generator#46]
when having an `set:enum` or `set:lenum` type attributes defined as `isSearchable = "true"` in the attributes CSV file, the resulting JSON file contains the flag `"isSearchable": false"`

**Comment by junajan** [comment]
@stmeissner @hajoeichler - In the code there is a condition which sets `isSearchable` and `isRequired` to `false` when the type is `set`:
https://github.com/sphereio/sphere-product-type-json-generator/blob/master/src/coffee/product-type-generator.coffee#L118

Is it a correct behavior? Or should I remove this condition?

**Comment by stmeissner** [comment]
yep @junajan, SetType attributes are searchable, but cannot be required:
https://dev.commercetools.com/http-api-projects-productTypes.html#settype

**Comment by junajan** [comment]
Fixed here https://github.com/sphereio/sphere-product-type-json-generator/pull/49.

**Comment by junajan** [comment]
merged
