### ISSUE TITLE
Support product type keys

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-product-type-json-generator#52]
### Description
We'd like to support product type keys (https://dev.commercetools.com/http-api-projects-productTypes.html#set-key) in the product type import, so that our users are not dependent from the "uuid" of the database.

**Comment by junajan** [comment]
Hello @Oehmi .. where would you like to add this support (which action/module)? Also, the productType.key is an optional parameter so maybe we can add support also for productType.name which is required and thus it is present in every productType.

**Comment by junajan** [comment]
Can be a duplicate of https://github.com/sphereio/sphere-product-type-json-generator/issues/51

**Comment by wizzy25** [comment]
From [here](https://dev.commercetools.com/http-api-projects-productTypes.html#producttypedraft) `key` is unique but not required, while `name` is required but not unique... I think sticking with the uuid is the best (only) option

**Comment by butenkor** [comment]
An option would be to make `key` mandatory if generator is to be used as also mandatory on type import through our tooling. Alternatively one could also use `name` as fallback (in case key is not defined) for a key. I would not use `name` or `UUID`

**Comment by junajan** [comment]
I agree with @butenkor ... let's use a `key` as a fallback value for `name` if it is not defined. @hisabimbola what do you think?

**Comment by junajan** [comment]
After the last discussion, we decided to support `uuid` and `key` - if neither of those two is provided `productType` will be skipped and the warning will be printed out.

**Comment by Oehmi** [comment]
@butenkor We want to go ahead with this issue and use **uuid** and **key**, as the name is not unique (like the ID) and two product types might have the same name. Are you fine with this solution?

**Comment by butenkor** [comment]
@Oehmi I am ok as long we support also key but i wonder why you want to support UUID as in your issue description you wanted to get rid of it? :)

**Comment by wizzy25** [comment]
We will go down the root of enforcing the `key` if the generator is to be used. This will however be a breaking change
