### ISSUE TITLE
Support deletion of product types

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-product-type-json-generator#53]
### Description

Please provide support for deleting product types inIMPEX, so that it is possible to "bulk delete" many product types without usage of the Admin Center. Types should be deletable by key as well. 
It would be nice if the respective matching products are removed as well once a product type is deleted.

**Comment by junajan** [comment]
Hello @Oehmi .. currently there are `product-type-generator` and `product-type-update` executables so we can add something like `product-type-delete`?

It would be a script which will take a CSV with one column named "names" (or "keys") and it will delete all matching productTypes and their products.

Let me know if you agree.

**Comment by junajan** [comment]
cc @hisabimbola @wi

**Comment by hisabimbola** [comment]
I am not sure about this, we do not support mass deletions at all, but we can start something towards deleting entities, a simple script/module will do.

**Comment by junajan** [comment]
What about this - we can create a new command page on Impex where you would select an entity (products, productTypes, ... ) then you would fill in a predicate (items which will match will be deleted) or you would provide a CSV file with column (eg key/name/id/...) and the list of all keys which should be deleted..

**Comment by wizzy25** [comment]
If we want to start mass deleting, then we should probably start it on most (all?) of our services, which is why I'm not sure if it's a good idea. And do we have one `delete` module for everything? Or each service would have a `delete` module? Or will it be for only `productTypes`?

**Comment by junajan** [comment]
I was thinking about one tool which would have a parameter where you can set what entity (productType/Products ... ) you want to delete.

**Comment by wizzy25** [comment]
A tool currently exists that can do this, so I will close this issue. Reopen if something more severe comes up @junajan @Oehmi @stmeissner 
https://github.com/wizzy25/sphere-deleter
