### ISSUE TITLE
[Impex] Importing Product Types does not work

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-product-type-json-generator#61]
### Support reference number
SUPPORT-3157

### Description
A client has reported that they cannot import productType after exporting the productType in Impex and trying to import it again using CSV. The error is "Cannot read the property "name" of undefined"

### Current Behavior
Steps to duplicate: 
export any product type ( via a predicate ) or all of them ( no predicate ), then use the import tool.

1- Using the ProductTypeExport to export all product types on a project.
2- Downloading the zip file and extracting it.
3- Opening the Product Type Import then choosing "tkaupat-dev" project.
4- Put the "attributes.csv" file in "Product Type attributes as CSV" section on the right.
5- Put the "products-to-attributes.csv" file in "Product Type template as CSV" to the left.
6- Run Command.

**Comment by daern91** [comment]
Fixed in [this release](https://github.com/sphereio/sphere-product-type-import/releases/tag/v2.0.1)
